# Generated by Django 3.1.5 on 2021-01-25 03:43

import CAHapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('displayName', models.CharField(default='', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=CAHapp.models.generate_code, max_length=6, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('num_rounds', models.IntegerField(default=10)),
                ('players', models.ManyToManyField(blank=True, to='CAHapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roomcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAHapp.room'),
        ),
    ]
