# Generated by Django 3.1.4 on 2021-01-18 06:34

import CAHapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=CAHapp.models.generate_code, max_length=6, unique=True)),
                ('host', models.CharField(default='', max_length=20, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('num_rounds', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAHapp.room')),
            ],
        ),
    ]
