# Generated by Django 3.1.5 on 2021-01-25 03:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
    ]
