# Generated by Django 3.1.4 on 2021-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='displayName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.CharField(max_length=10),
        ),
    ]
