# Generated by Django 3.1.4 on 2021-01-11 01:17

import CAHapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0002_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=CAHapp.models.generate_code, max_length=6),
        ),
    ]
