# Generated by Django 3.1.5 on 2021-01-27 05:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0002_person_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70), default=list, size=None),
        ),
    ]
