# Generated by Django 3.1.4 on 2021-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0004_auto_20210110_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_rounds',
            field=models.IntegerField(default=10),
        ),
    ]
