# Generated by Django 3.1.4 on 2021-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0005_remove_room_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='CAHapp.Person'),
        ),
    ]
