# Generated by Django 3.1.4 on 2021-01-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAHapp', '0006_auto_20210117_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAHapp.room'),
        ),
    ]
